### ISSUE TITLE
Common: Add manager to select user in cart form and attach to form

### ISSUE THREAD

**Issue by AndrewMaksimchuk** [AndrewMaksimchuk/radiomag#103]
### TODO:

Create new db table Managers and Shops

Change form in Cart page for select specific manager or shop globally
Create custom select component

### Definition of done:

- [x] checked manual testing
- [x] covered with unit/intagration tests
- [ ] has acceptable lighthouse score
