### ISSUE TITLE
Client: In cart, combine the same product together, sum up the quantity

### ISSUE THREAD

**Issue by AndrewMaksimchuk** [AndrewMaksimchuk/radiomag#106]
### TODO:

http://localhost:5173/cart

### Definition of done:

- [x] checked manual testing
- [x] covered with unit/intagration tests
- [ ] has acceptable lighthouse score
