### ISSUE TITLE
Server: Add seeds for database table

### ISSUE THREAD

**Issue by AndrewMaksimchuk** [AndrewMaksimchuk/radiomag#110]
### TODO:

Tables:
- [ ] cart
- [ ] order
- [ ] orderForm

### Definition of done:

- [ ] checked manual testing
- [ ] covered with unit/intagration tests
- [ ] has acceptable lighthouse score
