### ISSUE TITLE
Server: Endpoint for new orders + DB

### ISSUE THREAD

**Issue by AndrewMaksimchuk** [AndrewMaksimchuk/radiomag#95]
### TODO:

Add new endpoint for get order from user and write to database table with user connection.

### Definition of done:

- [x] checked manual testing
- [x] covered with unit/intagration tests
- [x] has acceptable lighthouse score
