### ISSUE TITLE
Client: Show all orders in user page

### ISSUE THREAD

**Issue by AndrewMaksimchuk** [AndrewMaksimchuk/radiomag#96]
### TODO:

After #95 

### Definition of done:

- [x] checked manual testing
- [x] covered with unit/intagration tests
- [ ] has acceptable lighthouse score
