### ISSUE TITLE
Client: In UserPage show window set in url query params

### ISSUE THREAD

**Issue by AndrewMaksimchuk** [AndrewMaksimchuk/radiomag#98]
### TODO:
<pre>
http://localhost:5173/user?window=orders
                             ^
                             |
                           component name in lowercase
</pre>
### Definition of done:

- [x] checked manual testing
- [ ] covered with unit/intagration tests
- [ ] has acceptable lighthouse score
